version: 2
jobs:
  build:
    docker:
      - image: eboraas/apache-php:latest
    steps:
      - checkout
      - run: echo building
  test:
    docker:
      - image: eboraas/apache-php:latest
    steps:
      - checkout
      - run: echo testing
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test